global:
  scrape_interval: 5s

scrape_configs:
  - job_name: tracegate
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials: tracegate-local-admin
    static_configs:
      - targets:
          - tracegate:9090
